dist: trusty
addons:
  apt:
    packages:
      - libgtest-dev
language: cpp
compiler: clang

before_script:
- cd /usr/src/gtest
- sudo cmake .
- sudo make
- sudo cp *.a /usr/lib

script:
- mkdir -p build
- cd build
- cmake ..
- cmake --build .
