dist: xenial
addons:
  apt:
    packages:
      - libgtest-dev
      - cmake
language: cpp

before_script:
- export BUILD_DIR=$(pwd)
- cd /usr/src/gtest
- sudo cmake .
- sudo make
- sudo cp *.a /usr/lib

script:
- cd $BUILD_DIR
- mkdir -p build
- cd build
- cmake ..
- cmake --build .
